### ISSUE TITLE
Warning: apps.json file is rename

### ISSUE THREAD

**Issue by hihackthis** [martibarri/simple-security-headers#1]
Hi

The file apps.json was rename:

From:

https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/apps.json

To

https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies.json

So, when I run the tool, I got this error:

```
[~] Checking Wappalyzer Regular Expressions...
Traceback (most recent call last):
  File "simple-security-headers.py", line 218, in <module>
    main()
  File "simple-security-headers.py", line 133, in main
    'https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/apps.json').text)['categories']
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 1 (char 5)
```
I fix this issue:

1) Replace the link in the lines 132 and 137 in simple-security-headers.py file:
2) Also in line 137, replace 'apps' for 'technologies', just like that:

'https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies.json').text)['apps']

To:

'https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/technologies.json').text)['technologies']

And works fine!

Great tool, thank you! :-)

**Comment by martibarri** [comment]
Thanks for letting me know and for opening the first issue!
The fix is exactly what you have proposed :smiley:
